In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [14]:
# Step 1: Load Your CSV Data
# Replace 'iris_data.csv' with the actual path to your CSV file
iris = pd.read_csv('IRIS.csv')
iris.head()

# Assuming your CSV file has columns 'sepal_length', 'sepal_width', 'petal_length', 'petal_width', and 'species'
# X = your_data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
# y = your_data['species']

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [15]:
iris.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [17]:
iris.shape 

(150, 5)

In [22]:
iris['species'].values

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [20]:
iris['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [23]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [24]:
iris.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [25]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [27]:
iris.describe(include='all')

sepal_length  sepal_width  petal_length  petal_width      species
count     150.000000   150.000000    150.000000   150.000000          150
unique           NaN          NaN           NaN          NaN            3
top              NaN          NaN           NaN          NaN  Iris-setosa
freq             NaN          NaN           NaN          NaN           50
mean        5.843333     3.054000      3.758667     1.198667          NaN
std         0.828066     0.433594      1.764420     0.763161          NaN
min         4.300000     2.000000      1.000000     0.100000          NaN
25%         5.100000     2.800000      1.600000     0.300000          NaN
50%         5.800000     3.000000      4.350000     1.300000          NaN
75%         6.400000     3.300000      5.100000     1.800000          NaN
max         7.900000     4.400000      6.900000     2.500000          NaN

In [28]:
#Now split the dataframe in X and y
X=iris.iloc[:,:4]
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [31]:
y=iris.iloc[:,-1] #-1 mean last column of dataframe seleted and : mean all row selected
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

Data Normalization

In [38]:
#because sepal_lenght and sepat width different unit
X = preprocessing.StandardScaler().fit_transform(X)
X[0:4] 


array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673]])

Train Test Split

In [39]:
from sklearn.model_selection import train_test_split
#test_size=0.3 mean 70% data for training and 30% for testing
#random_state=1 mean when we run again and again same selection will used
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)
y_test.shape #45 rows are randomly selected for testing

(45,)

Training and Predicting

In [41]:
knnModel=KNeighborsClassifier(n_neighbors=3) # 3 is value of K
knnModel.fit(X_train,y_train)
y_predict1=knnModel.predict(X_test)

C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\sklearn\neighbors\_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Accuracy 

In [44]:
# from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_predict1)
acc

0.9777777777777777

Confusion Matrix

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test.values,y_predict1)
cm

array([[14,  0,  0],
       [ 0, 18,  0],
       [ 0,  1, 12]], dtype=int64)

In [47]:
cm1=pd.DataFrame(data=cm,index=['setosa','versicolor','virginica'],columns=['setosa','versicolor','virginica'])
cm1

setosa  versicolor  virginica
setosa          14           0          0
versicolor       0          18          0
virginica        0           1         12

output Visualization

In [50]:
prediction_output=pd.DataFrame(data=[y_test.values,y_predict1],index=['y_test','y_predict1'])
prediction_output


0                1                2            3   \
y_test      Iris-setosa  Iris-versicolor  Iris-versicolor  Iris-setosa   
y_predict1  Iris-setosa  Iris-versicolor  Iris-versicolor  Iris-setosa   

                        4                5               6            7   \
y_test      Iris-virginica  Iris-versicolor  Iris-virginica  Iris-setosa   
y_predict1  Iris-virginica  Iris-versicolor  Iris-virginica  Iris-setosa   

                     8               9   ...           35               36  \
y_test      Iris-setosa  Iris-virginica  ...  Iris-setosa  Iris-versicolor   
y_predict1  Iris-setosa  Iris-virginica  ...  Iris-setosa  Iris-versicolor   

                     37               38              39              40  \
y_test      Iris-setosa  Iris-versicolor  Iris-virginica  Iris-virginica   
y_predict1  Iris-setosa  Iris-versicolor  Iris-virginica  Iris-virginica   

                     41               42              43               44  
y_test      Iris-setosa   Iris-virginica  Iris-virginica  Iris-versicolor  
y_predict1  Iris-setosa  Iris-versicolor  Iris-virginica  Iris-versicolor  

[2 rows x 45 columns]

In [51]:
prediction_output.T

y_test       y_predict1
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10  Iris-versicolor  Iris-versicolor
11      Iris-setosa      Iris-setosa
12   Iris-virginica   Iris-virginica
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25  Iris-versicolor  Iris-versicolor
26      Iris-setosa      Iris-setosa
27      Iris-setosa      Iris-setosa
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica
30  Iris-versicolor  Iris-versicolor
31   Iris-virginica   Iris-virginica
32  Iris-versicolor  Iris-versicolor
33   Iris-virginica   Iris-virginica
34   Iris-virginica   Iris-virginica
35      Iris-setosa      Iris-setosa
36  Iris-versicolor  Iris-versicolor
37      Iris-setosa      Iris-setosa
38  Iris-versicolor  Iris-versicolor
39   Iris-virginica   Iris-virginica
40   Iris-virginica   Iris-virginica
41      Iris-setosa      Iris-setosa
42   Iris-virginica  Iris-versicolor
43   Iris-virginica   Iris-virginica
44  Iris-versicolor  Iris-versicolor

In [55]:
prediction_output.iloc[0,:].value_counts()

Iris-versicolor    18
Iris-setosa        14
Iris-virginica     13
Name: y_test, dtype: int64

In [53]:
# Step 2: Pre-process the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Step 3: Explore the dataset (Optional)
# You can uncomment and run this code to visualize the dataset
plt.scatter(X['sepal_length'], X['sepal_width'], c=y, cmap='viridis')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.show()

In [ ]:
# Step 4: Select a machine learning algorithm
knn = KNeighborsClassifier(n_neighbors=3)  # Setting warn_on_dtype to False






In [ ]:
# Step 5: Train your model
knn.fit(X_train, y_train)



In [ ]:
# Step 6: Evaluate your model's performance
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [13]:

# Step 7: Use your model to make predictions on new data
# Example input for new data
new_data = [[5.1, 3.5, 1.4, 0.2]]  
predicted_species = knn.predict(new_data)
print("Predicted species:", predicted_species[0])

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.